### ISSUE TITLE
"Warning in install.packages :   package ‘riojaPlot’ is not available for this version of R"

### ISSUE THREAD

**Issue by Aspea496** [nsj3/riojaPlot#1]
I've been using riojaplot successfully up until Friday 23rd Jun, but yesterday and today (26/27th of Jun) I get the error that riojaplot is not available on this version of R. I've been using R-4.3.1 throughout, but have also tried on 4.2.2, 4.2.3, 4.3.0 and had the same issue. 
The issue persists on different computers and networks.

**Comment by nsj3** [comment]
How are you trying to install riojaPlot?  Did you use 
install.packages("riojaPlot", repos="https://nsj3.r-universe.dev") or
remotes::install_github("nsj3/riojaPlot", build_vignettes=TRUE, dependencies=TRUE)

These work for me on R 4.3.1

**Comment by Aspea496** [comment]
Thank you! The nsj3 repository worked for me.
